export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const SET_PRODUCT_ID = 'SET_PRODUCT_ID';
export const SET_CURRENT_IMAGE = 'SET_CURRENT_IMAGE';
export const SET_CURRENT_STYLE_IDX = 'SET_CURRENT_STYLE_IDX';
